# Specifying the base image
FROM python:3.12-bookworm

# Install system dependencies and pip
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    python3-pip

RUN apt install nano -y

# Install common python packages for development
RUN pip install --upgrade pip
RUN pip install black pytest coverage poetry 